/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Cube(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/goodAnimation.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Cube"
          castShadow
          receiveShadow
          geometry={nodes.Cube.geometry}
          material={materials["Material.003"]}
          position={[0.605, 0, 0]}
          scale={[0.3, 1, 1]}
        />
        <pointLight
          name="Point"
          intensity={760.92}
          decay={2}
          position={[-3.114, 4.264, 4.423]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/goodAnimation.glb");
